### PR TITLE
Image Classification models and GUI designs 

### PR DESCRIPTION
**Pull request by deveshruttala**
hey! I am devesh, a 2nd year Btech student from SRM University, i have some experience in Python, Pytorch and some image-processing models, victory interested me in working on it, so from the side of GSoC I would like to contribute to this project

here are some basic implementations and models that can be used to make this project possible.  I am show casing some designs and models that can be used here.

I am constantly working on this project and will be providing you continuous information regarding the progress and finding better and easy model solutions that can handle this project very well. more over  I would also propose some extra features that will bring more accessibility of the gallery page

I will also bring in more models built  using opencv, yolo, tensorflow or else extending the model support by using pipeling  pretrained models from hugging face that will give me accurate solutions

### CODE REVIEW

**Comment by deveshruttala** [comment]
comment me some suggestions and more requirements on this project @Pranav0-0Aggarwal

**Comment by deveshruttala** [comment]
i  think we can proceed with this type of layout along with a dashboard where users can add images,  we can process image details information right in the dashboard and add the obtained data in to the final gallery , where the details about the image can be stored right into the database

**Comment by Pranav0-0Aggarwal** [comment]
Hi @deveshruttala can we have discussion regarding this on Discord?
I think others input would be valuable in this.
Also a lot of UI and models have been prepared by other contributors, I recommend you checking them out once, before making a PR.

**Comment by deveshruttala** [comment]
> Hi @deveshruttala can we have discussion regarding this on Discord? I think others input would be valuable in this. Also a lot of UI and models have been prepared by other contributors, I recommend you checking them out once, before making a PR.

this is a sample design layout only  I improve and show case some better GUI designs further later @Pranav0-0Aggarwal

**Comment by Pranav0-0Aggarwal** [comment]
Change of Plans

**Pull request closed without merging**
