### PR TITLE
Bugfix/fix performance issues for image gallery

### LINKED ISSUE #120: BUG: RAM and CPU overload for higher quality images
### Is there an existing issue for this?

- [X] I have searched the existing issues

## What happened?

When we add a folder with very lightweight images (e.g. the tests folder in our repository), the gallery works fine and doesn't consume much resources: 

WhatsApp Image 2024-12-23 at 16 22 23_dd5abda2

But when I added a folder of only 330 MB, containing 73 images, the gallery took up almost 3.5 GB of RAM and 20-30% of continuous CPU usage on my laptop (Core i7 11th Gen with 16 GB RAM).  Also, if you view this video I captured using my phone(to avoid the influence of the screen recorder on performance), you will notice the performance issues when switching to the next page and scrolling. 

video(unlisted on YouTube): https://www.youtube.com/watch?v=gfWAamOvsdk

WhatsApp Image 2024-12-23 at 16 34 29_3cc4956a

## Proposed solution: 

1) To generate a folder named PictoPy.thumbnails inside the selected folder. 
2) This folder will contain resized images from its parent folder
3) This folder will not take up a lot of space. Only around 100 -300 kB per image. 
4) While displaying the gallery, we display images from this thumbnails folder, and when the user clicks the image to view it, we only bring up the original image. This will considerably improve the app's performance and limit the RAM usage to under 500 MB. 
5) To generate thumbnails, we need to use the well-known image processing library for Rust, which is [this](https://crates.io/crates/image). 
6) After generating the thumbnails, we also need to send paths for the thumbnails; for this, we need to modify the [get_images_with_cache()](https://github.com/AOSSIE-Org/PictoPy/blob/main/frontend/src-tauri/src/services/mod.rs#L34) function.

### Record

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by rahulharpal1603**
This PR fixes #120 

Demo video (Unlisted on YouTube): https://youtu.be/vTVKSk-Q5lY

1) In the Issue that I created, the app took up almost 3.5 GB of RAM to display 20 images. Now, after displaying just the thumbnails in the grid, we are able to keep the RAM usage around 500 MB, even if we try to display 4K images.

2) This thumbnail functionality is added for all the pages where images are displayed in a grid: 
      - Home Page
      - AI Tagging Page
      - Deletion page in AITagging
      - Album Images Page
      - Add Images to the Album page.
  
 3) I have also done some minor bug fixes: 
       - The default behaviour of dark mode was not functioning properly, so I fixed it
       -  Fixed the issues related to refetching album data after adding or deleting images by properly invalidating the query keys. This was possible due to the newly introduced tanstack query implementation.
       
### Note: 
  In the issue, I mentioned that I would use a Rust library to generate thumbnails, but it was just too slow, so I handled this task using our FastAPI server and Python's Pillow library

### CODE REVIEW

**Comment by rahulharpal1603** [comment]
@Pranav0-0Aggarwal Kindly review this.

**Comment by Pranav0-0Aggarwal** [comment]
Hi @rahulharpal1603 there's merge conflict, please resolve it.

Also can you elaborate more on your note added, if possible do add a demo video too.

**Comment by rahulharpal1603** [comment]
> Hi @rahulharpal1603 there's merge conflict, please resolve it.
> 
> Also can you elaborate more on your note added, if possible do add a demo video too.

About that note, the Rust's image processing library: https://crates.io/crates/image is able to generate thumnails for images but the underlying implementation is just too slow. Therefore, I used the Pillow library, which uses Python + C, so that it is way faster.  Now, I just hit an API Endpoint on the FastAPI server with folder path as the parameter, this generates the thumbnails for us and saves the thumbnail in the specified folder itself (within PictoPy.thumbnails folder).

Yes, I made the demo video, the link is mentioned in the PR. Or you want demo video of something else?

**Comment by rahulharpal1603** [comment]
> > Hi @rahulharpal1603 there's merge conflict, please resolve it.
> > Also can you elaborate more on your note added, if possible do add a demo video too.
> 
> About that note, the Rust's image processing library: https://crates.io/crates/image is able to generate thumnails for images but the underlying implementation is just too slow. Therefore, I used the Pillow library, which uses Python + C, so that it is way faster. Now, I just hit an API Endpoint on the FastAPI server with folder path as the parameter, this generates the thumbnails for us and saves the thumbnail in the specified folder itself (within PictoPy.thumbnails folder).
> 
> Yes, I made the demo video, the link is mentioned in the PR. Or you want demo video of something else?

**Comment by rahulharpal1603** [comment]
@Pranav0-0Aggarwal The conflicts are now resolved

**Comment by rahulharpal1603** [comment]
@Pranav0-0Aggarwal Here is the demo video to show the difference in processing speed of Rust library v/s Python's library: https://www.youtube.com/watch?v=OGkrEYsXm2U

As seen in the video, the Rust library takes far more time to process images than Python.

**Comment by Pranav0-0Aggarwal** [comment]
Great, sorry I missed out on the link initially.
merging it.

**Pull request merged**
