### PR TITLE
Feat: UI/UX Revamp (All tasks done)

### PR DESCRIPTION
**Pull request by rahulharpal1603**
Fixes all the subtasks of #113 

**Final Design**:

Demo Video (Unlisted):  https://www.youtube.com/watch?v=XsmDVfEm87c

Images: 

image

image

image

image

image

## Updates:
This pull request includes several changes aimed at improving the user interface and functionality of the application. The most important changes include updating the product name and window settings, modifying the gallery and album components, and refactoring the folder picker and media components.

### General Updates:
* Updated the product name to "PictoPy" and adjusted window settings in `tauri.conf.json`.

### NavBar and Sidebar now have a fresh look!:
* Applied relevant icons and smooth hover effect transitions to increase the usability and appeal

### Better Grid Layout:
* Made changes so that now the grid layout of images and videos adjust automatically after resizing the app. Previously, we used media queries which were not very flexible; now its flexible and more responsive

### Gallery and Album Enhancements:
* Increased the number of items per page from 9 to 20 in `AIgallery.tsx` and `MediaGallery.tsx`. [[1]](diffhunk://#diff-ee2e9fc5cd723343138de69d88fd4502487d09378b5458c3259d567fe4abfe9fL22-R22) [[2]](diffhunk://#diff-ba42837d638b1c700104ab605aff20f10ed326b799e0e15cffece72e7d16d553L21-R21)
* Modified the album view to refetch data on back navigation and improved the layout for album images and buttons in `Album.tsx` and `Albumview.tsx`. [[1]](diffhunk://#diff-45ffd420f922c6b9fd9fdb0953a6921f292328bc7800dbeb9662ec10d925f951L80-R99) [[2]](diffhunk://#diff-f3fab71b1e19dec3f2cac10e73774db13cd9de60e94dad5fd89c636314f61a22L71-R99)
* Updated the album card to display a placeholder icon when no images are present in `AlbumCard.tsx`.

### UI Improvements:
* Added a background color to the body in `App.css`.
* Enhanced the filter controls with new icons and improved button styling in `FilterControls.tsx`.

### Refactoring:
* Refactored the folder picker component to use new icons and added optional props for customization in `FolderPicker.tsx`.
* Improved the media card component to include a play icon overlay for videos in `MediaCard.tsx`.

### CODE REVIEW

**Comment by rahulharpal1603** [comment]
@Pranav0-0Aggarwal Please review this PR. The UI changes are done.

**Comment by Pranav0-0Aggarwal** [comment]
@rahulharpal1603 can you Resolve the conflicts.

**Comment by rahulharpal1603** [comment]
okay, let me see. 

> @rahulharpal1603 can you Resolve the conflicts.

**Comment by rahulharpal1603** [comment]
@Pranav0-0Aggarwal I think I should wait for this [PR](https://github.com/AOSSIE-Org/PictoPy/pull/132) to get merged because it has many files in common with this PR. After that, I will resolve the conflicts which occur due to that PR.

**Comment by Pranav0-0Aggarwal** [comment]
sure, then let's wait for @priyanshu9899 to fix the conflicts in issue #132

**Comment by Pranav0-0Aggarwal** [comment]
Priyanshu fixed the issue @rahulharpal1603

**Comment by rahulharpal1603** [comment]
> Priyanshu fixed the issue @rahulharpal1603

Okay, I will resolve the conflicts. This may take some time (an hour or so.)

**Comment by rahulharpal1603** [comment]
@Pranav0-0Aggarwal conflicts are resolved.

**Pull request merged**
