### PR TITLE
Implemented tanstack query and fixed few bugs

### LINKED ISSUE #137: Feat: Implementation of react tanstack query
### Describe the feature

Instead of manually handling data from backend we can implement a custom implementation of tanstack query, which will make the code more scalable. In future if we want to add more api calls and want more complex data handling, it will be very easy to manage with this. It will reduce code duplication and prop drilling by a lot. But if the functionality of the app is limited to what it is now then I think just context api or this code will be sufficient

### Add ScreenShots

no screenshots to attatch

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by Rishab87**
I have implemented tanstack query, improving api handling and making code more scalable. This PR fixes #137

### CODE REVIEW

**Comment by rahulharpal1603** [comment]
Hi @Rishab87 ! Can we also have some documentation for the process of adding new API Endpoints and using them by using usePictoMutation so that all the contributors can follow a similar standard? I think it can be added to the CONTRIBUTING.md file so that no one misses out on the code practices that we are going to follow from now on if we merge this PR. 

As a contributor myself, it would be great to use this, and can simplify the development process.

**Comment by Rishab87** [comment]
@rahulharpal1603 yes, I think that would be great, need to create a seperate issue for it, also I think readme for setting up project should also be updated as I had to figure many things on my own while setting up which is not beginner friendly.

**Comment by rahulharpal1603** [comment]
> @rahulharpal1603 yes, I think that would be great, need to create a seperate issue for it, also I think readme for setting up project should also be updated as I had to figure many things on my own while setting up which is not beginner friendly.

Yes, can you open the issue and work on it,? because you would be knowing the most about this PR and all its details. 

Also, the setup guide is not that great 😅 I can agree. The issue for setup guide can be separate and can be handled by someone else.

**Comment by rahulharpal1603** [comment]
I am telling you this because the issue I am working on, #120, introduces a new API endpoint in the FastAPI server, and I need to integrate it with Tanstack.

**Comment by Rishab87** [comment]
@rahulharpal1603 , sure I'll add it but first let this issue merge because without that its not confirmed and also I may need to do some changes here so no point of updating documentation now.

For now the structure of response I decided on is:
```
  return JSONResponse(
            status_code=200,
            content={
                "data": file_path,
                "message": "Image deleted successfully",
                "success": True
            }
        )
```

**Comment by rahulharpal1603** [comment]
> @rahulharpal1603 , sure I'll add it but first let this issue merge because without that its not confirmed and also I may need to do some changes here so no point of updating documentation now.
> 
> For now the structure of response I decided on is:
> 
> ```
>   return JSONResponse(
>             status_code=200,
>             content={
>                 "data": file_path,
>                 "message": "Image deleted successfully",
>                 "success": True
>             }
>         )
> ```

sure, we can wait for this to merge.

**Comment by Rishab87** [comment]
@rahulharpal1603 , now you can refer to this response returned by backend to write your api routes

**Comment by rahulharpal1603** [comment]
> @rahulharpal1603 , now you can refer to this response returned by backend to write your api routes 

Also, share the steps for the frontend. A formal documentation would be great

**Comment by Rishab87** [comment]
@rahulharpal1603 for frontend use usePictoQuery for get requests and mutation for other types of requests, you can invalidate get request data with autoInvalidateTags on mutation function, just write the queryKey used on usePictoQuery, for more details of how it works you can refer to docs or just send me a message on dc if you need any help.

**Comment by Dushyantbha012** [comment]
@Rishab87 Could you please explain why have you deleted AI_image.ts, Albumservice.ts and DeleteImage.ts in hooks
?

**Comment by Rishab87** [comment]
@Dushyantbha012 because they were being used for sending api calls , now that api calls and data handling are simplified with tanstack query we don't need those files that was the point of this update, to reduce boilerplate code , many states and prop drilling.

**Comment by Dushyantbha012** [comment]
Some files are using them and they are not updated then as of now, when i am building the app i am getting a lot of issues
check frontend/src/components/Album/ImageManagementDialog.tsx

**Comment by Rishab87** [comment]
@Dushyantbha012 I changed all files and I just looked that I've not updated this file , sorry for the inconvinience , I've now updated this file pushing it

**Comment by Rishab87** [comment]
@Dushyantbha012 I've pushed the change

**Pull request merged**
