### PR TITLE
feat(ui): enhance sidebar responsiveness for split-screen scenarios

### PR DESCRIPTION
**Pull request by asmit27rai**
# feat(ui): enhance sidebar responsiveness for split-screen scenarios
# issue: #147 

## Description
This PR improves the responsiveness of the sidebar in **PictoPy**, addressing issues observed when the application is used in split-screen mode or resized on desktop. The update ensures a seamless and visually appealing experience across varying screen sizes.

---

### Changes Introduced
1. **Responsive Sidebar:**
   - Added `overflow-y-auto` to allow smooth scrolling for the sidebar.
   - Dynamically adjusted the sidebar layout and width using responsive utilities.
   
2. **Hidden Scrollbars:**
   - Implemented a `scrollbar-hide` class to hide scrollbars across all browsers.
   - Enabled smooth scrolling with `WebkitOverflowScrolling: 'touch'` for touch device support.

---

### Video

https://github.com/user-attachments/assets/105b8f31-ead9-41f6-8e99-adcecf9d5cdc

### CODE REVIEW

**Comment by asmit27rai** [comment]
@Pranav0-0Aggarwal pls review the pr

**Comment by rahulharpal1603** [comment]
Hi @asmit27rai can you check whether the sidebar is occupying the full height of the screen when the window is maximized?

On my laptop the sidebar only takes up approx. half the screen after this commit.

**Comment by asmit27rai** [comment]
> Hi @asmit27rai can you check whether the sidebar is occupying the full height of the screen when the window is maximized?
> 
> On my laptop the sidebar only takes up approx. half the screen after this commit.

Yes I Think You Are Right.
But I Thought This Will Look Better. 
If Not Then I will make a PR For This ?

**Comment by rahulharpal1603** [comment]
> > Hi @asmit27rai can you check whether the sidebar is occupying the full height of the screen when the window is maximized?
> > 
> > On my laptop the sidebar only takes up approx. half the screen after this commit.
> 
> Yes I Think You Are Right.
> But I Thought This Will Look Better. 
> If Not Then I will make a PR For This ?

I think the previous size was better looking, utilised more area

**Comment by asmit27rai** [comment]
@rahulharpal1603 @Pranav0-0Aggarwal PR Made For This 
#181

**Pull request merged**
