### PR TITLE
Fix Navigation and Boundary Issues in MediaView Component

### PR DESCRIPTION
**Pull request by asmit27rai**
## Navigation and Boundary Issues

Fixes: #173

- This PR resolves navigation and boundary issues in the MediaView component, ensuring a seamless user experience when navigating through media items. The navigation logic has been refined to handle boundary cases effectively, preventing errors or inconsistencies when reaching the start or end of the media list. Additionally, UI adjustments have been made to maintain a consistent and user-friendly interface for both images and videos. These changes improve the overall reliability and usability of the component, providing a smoother and more intuitive experience for users.

### CODE REVIEW

**Comment by asmit27rai** [comment]
@Pranav0-0Aggarwal review the PR

**Review by Pranav0-0Aggarwal — COMMENTED** [review]
Merge Check

**Comment by asmit27rai** [comment]
@Pranav0-0Aggarwal Resolved

**Comment by Pranav0-0Aggarwal** [comment]
Another Merge conflict

**Comment by asmit27rai** [comment]
> Another Merge conflict

resolved

**Pull request merged**
